# Site settings
title: Deep South
description: > # this means to ignore newlines until "baseurl:"
  Testbed for simple conversation and deep learning algorithms.
baseurl: "/deep-south"
exclude: [ .idea ]

# Build settings
markdown: kramdown
